In [1]:
from google.colab import files
uploaded = files.upload()

Saving ecommerce_missing_duplicates_50_records.csv to ecommerce_missing_duplicates_50_records.csv

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("ecommerce_missing_duplicates_50_records.csv")

In [3]:
#Identify and count missing values
df.isnull().sum()

Order_ID       0
Product        1
Category       1
Unit_Price     1
Quantity       1
City           2
Order_Date     1
Customer_ID    1
dtype: int64

In [4]:
#Find repeated orders
df[df.duplicated(subset=["Order_ID"], keep=False)]

,Order_ID,Product,Category,Unit_Price,Quantity,City,Order_Date,Customer_ID
0,ORD2001,Laptop,Electronics,55000.0,1.0,Chennai,2026-03-01,CUST01
13,ORD2014,Smartphone,Electronics,25000.0,2.0,Bangalore,2026-03-07,CUST14
50,ORD2001,Laptop,Electronics,55000.0,1.0,Chennai,2026-03-01,CUST01
51,ORD2014,Smartphone,Electronics,25000.0,1.0,Bangalore,2026-03-07,CUST14

In [5]:
df["Order_ID"].duplicated().sum()

np.int64(2)

In [6]:
#Identify the highest-priced product
df.loc[df["Unit_Price"].idxmax(), ["Product", "Unit_Price"]]

Product        Laptop
Unit_Price    55000.0
Name: 0, dtype: object

In [7]:
#Calculate total revenue grouped by city
df["Revenue"] = df["Unit_Price"] * df["Quantity"]

df.groupby("City")["Revenue"].sum().sort_values(ascending=False)

City
Chennai      422300.0
Bangalore    314900.0
Mumbai       268800.0
Delhi        188900.0
Hyderabad    125400.0
Name: Revenue, dtype: float64